[package]
name = "sozu"
version = "0.1.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]

[dependencies]
mio = "^0.6"
mio-uds = "^0.6"
serde = "~0.8"
serde_json = "~0.8"
serde_derive = "~0.8"
nom = "^2.0"
nix  = "^0.7"
time = "^0.1.34"
clap = "^2.19.0"
slab = "^0.3.0"
libc = "^0.2"
rand = "^0.3.14"

[target.'cfg(target_os="linux")'.dependencies]
procinfo = { git = "https://github.com/BlackYoup/procinfo-rs", branch = "limits" }

[dependencies.sozu-lib]
path = "../lib"

[dependencies.sozu-command-lib]
path = "../command"

[features]
unstable = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
