# sozu proxy test config file

command_socket = "./command_folder/sock"
saved_state    = "./state.json"
log_level      = "info"
command_buffer_size = 16384

[metrics]
address = "192.168.59.103"
port = 8125

[proxies]

[proxies.HTTP]
address = "127.0.0.1"
proxy_type = "HTTP"
max_connections = 500
port = 8080
buffer_size = 16384
#answer_404 = "./404.html"
#answer_503 = "./503.html"

[proxies.TLS]
address = "127.0.0.1"
proxy_type = "HTTPS"
max_connections = 500
port = 8443
buffer_size = 16384
#default_app_id = "xxx"
#default_certificate = "../assets/cert_test.pem"
#default_certificate_chain = "../assets/cert__chain_test.pem"
#default_key = "../assets/key_test.pem"

#answer_404 = "./404.html"
#answer_503 = "./503.html"

[applications]

[applications.ABCD]
hostname   = "example.com"
path_begin = "/api" # optional
certificate = "../assets/certificate.pem" # optional
key = "../assets/key.pem" # optional
certificate_chain = "../assets/certificate_chain.pem" # optional
frontends = ["HTTP", "TLS"] # list of proxy tags
backends  = [ "127.0.0.1:1026" ] # list of IP/port

