# sozu proxy test config file

command_socket = "./command_folder/sock"
saved_state    = "./state.json"
log_level      = "info"
command_buffer_size = 16384

[metrics]
address = "192.168.59.103"
port = 8125

[listeners]

[listeners.HTTP]
address = "127.0.0.1"
listener_type = "HTTP"
max_connections = 500
port = 8080
buffer_size = 16384
#answer_404 = "./404.html"
#answer_503 = "./503.html"

[listeners.TLS]
address = "127.0.0.1"
listener_type = "HTTPS"
max_connections = 500
port = 8443
buffer_size = 16384
#default_app_id = "xxx"
#default_certificate = "../assets/cert_test.pem"
#default_certificate_chain = "../assets/cert__chain_test.pem"
#default_key = "../assets/key_test.pem"

#answer_404 = "./404.html"
#answer_503 = "./503.html"

