
before_script:
  - echo $TOTO_VAR

rustbuild-1.5:
  image: waxzce/rust-1.5-nginx:latest
  script:
    - rustc -V
    - echo "ubuntu install date"
    - cat /ubuntu_update_date.txt
    - echo "rust install date"
    - cat /rust_update_date.txt
    - cargo build
    - cargo test
    - cd yxorp && cargo test
    - cd ..
    - ./docker_tests/run_nginx.sh
    - RUST_LOG=info ./target/debug/examples/main &
    - sleep 5
    - curl --max-time 10 -v http://lolcatho.st:8080/
    - curl --max-time 10 -vk https://lolcatho.st:8443/

rustbuild-1.6:
  image: waxzce/rust-1.6-nginx:latest
  script:
    - rustc -V
    - echo "ubuntu install date"
    - cat /ubuntu_update_date.txt
    - echo "rust install date"
    - cat /rust_update_date.txt
    - cargo build
    - cargo test
    - cd yxorp && cargo test
    - cd ..
    - ./docker_tests/run_nginx.sh
    - RUST_LOG=info ./target/debug/examples/main &
    - sleep 5
    - curl --max-time 10 -v http://lolcatho.st:1026/
    - curl --max-time 10 -v http://lolcatho.st:8080/
    - curl --max-time 10 -vk https://lolcatho.st:8443/


rustbuild-1.7:
  image: waxzce/rust-1.7-nginx:latest
  script:
    - rustc -V
    - echo "ubuntu install date"
    - cat /ubuntu_update_date.txt
    - echo "rust install date"
    - cat /rust_update_date.txt
    - cargo build
    - cargo test
    - cd yxorp && cargo test
    - cd ..
    - ./docker_tests/run_nginx.sh
    - RUST_LOG=info ./target/debug/examples/main &
    - sleep 5
    - curl --max-time 10 -v http://lolcatho.st:8080/
    - curl --max-time 10 -vk https://lolcatho.st:8443/
