[package]
name = "yxorp"
version = "0.1.0"
authors = ["Clément Delafargue <clement@delafargue.name>", "Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
rand = "^0.3.14"
nom = "~1.2.0"
slab = "^0.1.3"
time = "^0.1.34"
mio = "~0.5.0"
bytes = "~0.3.0"
log = "0.3"
rustc-serialize = "0.3.15"
lazy_static = "0.1.15"

[dev-dependencies]
tiny_http= "0.4"
env_logger = "0.3"

[dependencies.openssl]
version = "~0.7.0"
features = ["tlsv1_2", "tlsv1_1", "rfc5114", "ecdh_auto"]

[dependencies.pool]
git = "https://github.com/Geal/pool.git"

[dependencies.uuid]
version = "~0.2.0"
features = ["v4"]

[features]
default = []
splice  = []
