[package]
name = "yxorp"
version = "0.1.0"
authors = ["Clément Delafargue <clement@delafargue.name>", "Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
rand = "*"
nom = "~1.0.0"
slab = "*"
time = "*"
mio = "~0.4.0"
libc = "*"
log = "0.3"
env_logger = "0.3"
rustc-serialize = "0.3.15"
openssl = "~0.7.0"

[dependencies.amqp]
git = "https://github.com/Geal/rust-amqp"

[dev-dependencies.tiny_http]
version = "0.4"

[features]
default = []
splice  = []
