[package]
name = "yxorp"
version = "0.1.0"
authors = ["Clément Delafargue <clement@delafargue.name>", "Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
nom = "~0.3.1"
slab = "*"
time = "*"
mio = "~0.4.0"
libc = "*"

[features]
default = []
splice  = []
