[package]
name = "yxorp"
version = "0.1.0"
authors = ["Clément Delafargue <clement@delafargue.name>", "Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
rand = "*"
nom = "~1.1.0"
slab = "*"
time = "*"
mio = "~0.5.0"
bytes = "~0.3.0"
libc = "*"
log = "0.3"
env_logger = "0.3"
rustc-serialize = "0.3.15"
lazy_static = "0.1.15"

[dev-dependencies.tiny_http]
version = "0.4"

[dependencies.openssl]
version = "~0.7.0"
features = ["tlsv1_2", "tlsv1_1"]

[features]
default = []
splice  = []
