[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "http://sozu.io"
version = "0.1.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]

[dependencies]
log = "0.3"
serde = "^0.9.13"
serde_json = "^0.9.9"
serde_derive = "^0.9.13"
openssl = "^0.9.5"
sozu-lib = "^0.1"

[dependencies.toml]
version = "^0.3"
default-features = false
features = ["serde"]

[features]
unstable = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
