[package]
name = "sozu-command-lib"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
log = "0.3"
serde = "^0.8"
serde_json = "^0.8"
serde_derive = "^0.8"

[dependencies.toml]
version = "^0.2"
default-features = false
features = ["serde"]

[dependencies.sozu-lib]
path = "../lib"
