[package]
name = "sozuctl"
version = "0.1.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
time    = "^0.1.34"
clap    = "^2.19.0"
libc    = "^0.2"
nix     = "^0.7"
mio     = "^0.6"
mio-uds = "^0.6"
rand    = "^0.3"

[dependencies.sozu-lib]
path = "../lib"

[dependencies.sozu-command-lib]
path = "../command"
