[package]
name = "sozuctl"
version = "0.1.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
time = "^0.1.34"
clap = "^2.19.0"
libc = "^0.2"
nix  = "^0.7"
mio = "^0.6"
mio-uds = "^0.6"
serde   = "~0.8"
serde_json = "~0.8"
serde_derive = "~0.8"

[dependencies.toml]
version = "^0.2"
default-features = false
features = ["serde"]

[dependencies.sozu-lib]
path = "../lib"
