# yxorp test config file

command_socket = "./command_folder/sock"
saved_state    = "./conf_dump.json"
log_level      = "info"
command_buffer_size = 12000

[metrics]
address = "192.168.59.103"
port = 8125

[listeners]

[listeners.HTTP]
address = "127.0.0.1"
listener_type = "HTTP"
max_connections = 500
port = 8080
buffer_size = 12000

#answers configuration is not active yet
#answer_404 = "./404.html"
#answer_503 = "./503.html"

[listeners.TLS]
address = "127.0.0.1"
listener_type = "HTTPS"
max_connections = 500
port = 8443
buffer_size = 12000
#answer_404 = "./404.html"
#answer_503 = "./503.html"

